name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container: openjdk
    steps:
      - uses: actions/checkout@v2
      - name: Build Project
        run: javac -cp "junit-4.10.jar:." *.java
  calcadd:
    runs-on: ubuntu-latest
    container: openjdk
    steps:
      - uses: actions/checkout@v2
      - name: Test Calc Add 
      - run: |
          javac -cp "junit-4.10.jar:.*" *.java
          java -cp "junit-4.10.jar:." org.junit.runner.JUnitCore TestAdd
  calcsub:
    runs-on: ubuntu-latest
    container: openjdk
    steps:
      - uses: actions/checkout@v2
      - name: Test Calc Sub
      - run: |
          javac -cp "junit-4.10.jar:.*" *.java
          java -cp "junit-4.10.jar:." org.junit.runner.JUnitCore TestSub
